sharding:
  jdbc:
    datasource:
      ds0:
        password: wangyang
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.24.0.221:3306/shard_1
        username: root
      ds1:
        password: wangyang
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://118.24.0.221:3306/shard_2
        username: root
      names: ds0,ds1
    config:
      sharding:
        tables:
          employee:
            actual-data-nodes: ds$->{0..1}.employee_$->{0..1}
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: employee_$->{id % 2}
        default-table-strategy:
          standard:
            sharding-column: code
            precise-algorithm-class-name: com.dave.sharding.custom.route.CommonDataBaseStrategy


#分表算法节点
murmur:
  node: 2
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
